# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('descriptions', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
